sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker
before_install: 
  - docker build -t sukritsachdeva/docker-react -f Dockerfile.dev .
scripts:
  - docker run sukritsachdeva/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-472410407232"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"