sudo: required

language: node_js

services:
  - docker

before_install: 
  - docker build -t sukritsachdeva/docker-react -f Dockerfile.dev .

scripts:
  - docker run sukritsachdeva/docker-react npm run test -- --coverage